// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/sign-in": {
    params: {};
  };
  "/sign-up": {
    params: {};
  };
  "/verify-email": {
    params: {};
  };
  "/forgot-password": {
    params: {};
  };
  "/reset-password": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/sign-in" | "/sign-up" | "/verify-email" | "/forgot-password" | "/reset-password";
  };
  "./routes/auth/auth-layout.tsx": {
    id: "routes/auth/auth-layout";
    page: "/" | "/sign-in" | "/sign-up" | "/verify-email" | "/forgot-password" | "/reset-password";
  };
  "./routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "./routes/auth/sign-in.tsx": {
    id: "routes/auth/sign-in";
    page: "/sign-in";
  };
  "./routes/auth/sign-up.tsx": {
    id: "routes/auth/sign-up";
    page: "/sign-up";
  };
  "./routes/auth/verify-email.tsx": {
    id: "routes/auth/verify-email";
    page: "/verify-email";
  };
  "./routes/auth/forgot-password.tsx": {
    id: "routes/auth/forgot-password";
    page: "/forgot-password";
  };
  "./routes/auth/reset-password.tsx": {
    id: "routes/auth/reset-password";
    page: "/reset-password";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/auth/auth-layout": typeof import("./app/./routes/auth/auth-layout.tsx");
  "routes/home": typeof import("./app/./routes/home.tsx");
  "routes/auth/sign-in": typeof import("./app/./routes/auth/sign-in.tsx");
  "routes/auth/sign-up": typeof import("./app/./routes/auth/sign-up.tsx");
  "routes/auth/verify-email": typeof import("./app/./routes/auth/verify-email.tsx");
  "routes/auth/forgot-password": typeof import("./app/./routes/auth/forgot-password.tsx");
  "routes/auth/reset-password": typeof import("./app/./routes/auth/reset-password.tsx");
};